### ISSUE TITLE
Handling HTML entities via mbstring is deprecated in PHP 8.2

### ISSUE THREAD

**Issue by aboks** [caxy/php-htmldiff#120]
When using this library with PHP 8.2 it yields deprecation warnings like
```
Deprecated:  mb_convert_encoding(): Handling HTML entities via mbstring is deprecated; use htmlspecialchars, htmlentities, or mb_encode_numericentity/mb_decode_numericentity instead in [...]/vendor/caxy/php-htmldiff/lib/Caxy/HtmlDiff/ListDiffLines.php on line 87
```

**Comment by Ambient-Impact** [comment]
I'm still getting this but for `TableDiff`:

> Deprecated function: mb_convert_encoding(): Handling HTML entities via mbstring is deprecated; use htmlspecialchars, htmlentities, or mb_encode_numericentity/mb_decode_numericentity instead in Caxy\HtmlDiff\Table\TableDiff->createDocumentWithHtml() (line 630 of /var/www/html/vendor/caxy/php-htmldiff/lib/Caxy/HtmlDiff/Table/TableDiff.php).

**Comment by sarahwylie** [comment]
I'm receiving the same error as @Ambient-Impact - any possible solutions yet?

**Comment by Ambient-Impact** [comment]
@sarahwylie Not much I can do but there's open pull request #125 which should fix the PHP notice when it's merged. If you need it sooner, you can try pointing Composer to that pull request or patching the package yourself.
