### ISSUE TITLE
encoding

### ISSUE THREAD

**Issue by gondo** [caxy/php-htmldiff#22]
one of the parameter for constructor in `AbstractDiff` class is `$encoding`, however this is not used anywhere. 
is something missing? what is the point of it?

**Comment by jschroed91** [comment]
@gondo Good point... I took a look at the upstream repo and it's not being used there either... do you have a need for implementation of handling encoding?

**Comment by gondo** [comment]
replace every string related function with its `mb_*` equivalent
http://php.net/manual/en/book.mbstring.php

**Comment by jschroed91** [comment]
Sounds good!

**Comment by jschroed91** [comment]
@gondo Just an update - I plan to include implementation for encoding in the next release. Aiming for 1-2 weeks.

**Comment by jschroed91** [comment]
I believe the changes made in #72 address these issues. Please reopen this issue if that's not the case.
