### ISSUE TITLE
Detecting link changes

### ISSUE THREAD

**Issue by maliayas** [caxy/php-htmldiff#28]
It seems, neither this fork nor the upstream can detect link changes. For example:

````diff
-<a href="http://lorem.com">this part doesn't change</a>
+<a href="http://ipsum.com">this part doesn't change</a>
````

GitHub rich text diff plays nice with this case. Styling is not in the scope of this library but I've captured some screenshots for inspiration. If a`href` attribute is changed, GitHub dotted-underlines it and presents a tooltip:

![ekran goruntusu 2016 02 21 22_25_38](https://cloud.githubusercontent.com/assets/844008/13205174/5603a81c-d8ea-11e5-9109-efe48be9e76d.png)

Tooltip:

![ekran goruntusu 2016 02 21 22_25_47](https://cloud.githubusercontent.com/assets/844008/13205175/57f27234-d8ea-11e5-9f11-ff8bb911041d.png)

If link text is also changed, underline and tooltip is gone:

![ekran goruntusu 2016 02 21 22_26_10](https://cloud.githubusercontent.com/assets/844008/13205177/598f4d56-d8ea-11e5-946d-30434c7cf5c7.png)

Could we have this detection in this library? Thanks in advance.

**Comment by jschroed91** [comment]
Of course! I'm working on the table diffing feature now, I will try to sneak this in early this week. Unless someone else wants to put in a PR

**Comment by maliayas** [comment]
Thanks very much!

**Comment by jschroed91** [comment]
@maliayas Just merged in updates to detect link changes - I didn't do anything fancy with tooltips since that is out of the scope of this library. But if a link is changed, the old link will be wrapped in a `<del class="diffmod diff-href"></del>` and the new link will be wrapped in `<ins class="diffmod diff-href"></ins>`

**Comment by maliayas** [comment]
Lovely! Problem solved. Btw I've made a code review to be helpful.

**Comment by jschroed91** [comment]
It's very appreciated! Thank you @maliayas - I will look at your comments and make updates either today or tomorrow morning.

Feel free to suggest additional features/bug fixes in the future, and you are welcome to contribute / open PRs.

We don't have any documentation on contributing at this point, but I hope to do some major clean-up of the code and put together some documentation sometime in the near future.

**Comment by maliayas** [comment]
Very nice to hear this. Thanks.
