### ISSUE TITLE
Crashes if string contains "Р" character (uppercase cyrillic Р letter)

### ISSUE THREAD

**Issue by Rastishka** [caxy/php-htmldiff#58]
Please add  "/u" (PCRE_UTF8) modifier to regexps, if  $config->setEncoding('UTF-8') is set.

**Comment by jschroed91** [comment]
Thank you for submitting this issue @Rastishka - I will be able to make this change sometime this weekend, but if you need it sooner feel free to fork and make the changes and open a pull request!

**Comment by SavageTiger** [comment]
Hi Josh,

I took the time to look at this issue. However it seems invalid. I cannot for the live of me reproduce this issue. Maybe its only present in a certain PHP version.

Testing the following fixture seems to work fine:

<oldText>
    <div>&#1056; ҦԤП п; italics: П п</div>
</oldText>

<newText>
    <div>Its all gone!</div>
</newText>

<expected>
    <div><del class="diffmod">Р ҦԤП п; italics: П п</del><ins class="diffmod">Its all gone!</ins></div>
</expected>

Maybe the ticket should be closed?

**Comment by jschroed91** [comment]
@Rastishka Closing this issue based on comment above - if this is still an issue please reopen and provide example text input for us to reproduce

**Comment by jschroed91** [comment]
Thank you @SavageTiger!
