### ISSUE TITLE
Does not work on PHP 5.3.10

### ISSUE THREAD

**Issue by myfriend12** [caxy/php-htmldiff#61]
The ListDiffLines.php file uses [ ] as declaring arrays which is not supported in PHP 5.3 so composer will need to be updated to be greater than 5.3 or the array declaration will need to be changed.

"As of PHP 5.4 you can also use the short array syntax, which replaces array() with []."

**Comment by myfriend12** [comment]
Line 63 of LcsServices.php also has the same issue.

**Comment by jschroed91** [comment]
@myfriend12 Is this the only compatibility issue with 5.3? If so, I'm okay with updating it to use `array()` instead of `[]` in order to restore 5.3 support

**Comment by myfriend12** [comment]
Yes, from what I can see running on my code that is the only compatibility issue. I did a fork and pull which just passed the tests.

**Comment by jschroed91** [comment]
Thank you @myfriend12! This has been merged, and I can tag a new release

**Comment by jschroed91** [comment]
Tagged a new release v0.1.4 with this fix

**Comment by myfriend12** [comment]
Awesome thanks. Love this package by the way.
