### ISSUE TITLE
del inside ins

### ISSUE THREAD

**Issue by tester20000** [caxy/php-htmldiff#69]
Hi,
This is my test:

`$a='<b><i>test</i></b>';`
`$b='<i>test</i>';`

`$htmlDiffConfig = new \Caxy\HtmlDiff\HtmlDiffConfig();`
`$htmlDiff = \Caxy\HtmlDiff\HtmlDiff::create($a, $b, $htmlDiffConfig);`
`echo $htmlDiff->build();`

result:

`<i class="diffmod">`
`<ins class="mod">`
`<del class="diffmod">test</del>`
`</i>`
`</b>`
`<i class="diffmod">`
`<ins class="mod">`
`<ins class="diffmod">test</ins>`
`</i>`

missing `</ins>`.
why is there a `</b>`?
I can't write a proper css, because there is a del tag inside an ins tag.

Please help!

**Comment by SavageTiger** [comment]
This could be related to https://github.com/caxy/php-htmldiff/pull/108, maybe good to retry once 0.1.14 is released.

**Comment by SavageTiger** [comment]
There is a really good chance that this problem is fixed in this release; https://github.com/caxy/php-htmldiff/releases/tag/v0.1.14

In case the problem persists feel free to reopen this issue or create a new one.
