### ISSUE TITLE
Class 'Caxy\HtmlDiff\AbstractDiff' not found

### ISSUE THREAD

**Issue by harrysrevis** [caxy/php-htmldiff#87]
Tried to install the lib in codeigniter and i get this error...

Any ideas?!

**_Fatal error: Class 'Caxy\HtmlDiff\AbstractDiff' not found_**

**Comment by SavageTiger** [comment]
I don't think this ticket has anything todo with the package? I suggest we close it.

**Comment by SavageTiger** [comment]
I have closed this ticket due to inactivity and no other complaints from other users making me wonder if this is a problem with the library itself.

Feel free to re-open a ticket if the problem persists.
