### ISSUE TITLE
Problem with Match in PHP8

### ISSUE THREAD

**Issue by vagifrzada** [caxy/php-htmldiff#94]
**Caxy\HtmlDiff\Match** class is not usable because of **PHP8 "match"** reserved key.
So, obviously, diffing is not working in PHP8. It needs refactoring (Renaming class name to **Matcher** at least)

**Comment by taz77** [comment]
The maintainers here have already started working on it: https://github.com/caxy/php-htmldiff/tree/sven/upgrade/php8

**Comment by SavageTiger** [comment]
I was waiting on feedback from @jschroed91 but I think he is a bit too busy, so I'll make a release soon.

**Comment by jschroed91** [comment]
@SavageTiger You can go ahead with this without my review, thank you so much! Working on a product launch this week so I won't be able to take a look for a bit and don't want to be a blocker on this.

**Comment by SavageTiger** [comment]
I just released version v0.1.10 that fixes the issue
